package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"
)

var (
	interfaceName  string
	targetSSID     string
	wpaConfPath    string
	scanIntervalSec int
)

const (
	StrongSignalDbm = -50
	WeakSignalDbm   = -75
)

func init() {
	flag.StringVar(&interfaceName, "i", "wlan0", "Wireless interface name")
	flag.StringVar(&targetSSID, "s", "#HOME-WIFI", "Target SSID to survey")
	flag.StringVar(&wpaConfPath, "c", "/etc/wpa_supplicant.conf", "Path to wpa_supplicant.conf")
	flag.IntVar(&scanIntervalSec, "t", 30, "Scan interval in seconds")
}

func main() {
	flag.Parse()

	scanInterval := time.Duration(scanIntervalSec) * time.Second

	fmt.Println("--- Wi-Fi Survey Configuration ---")
	fmt.Printf("Interface:       %s\n", interfaceName)
	fmt.Printf("Target SSID:     %s\n", targetSSID)
	fmt.Printf("Config Path:     %s\n", wpaConfPath)
	fmt.Printf("Scan Interval:   %v\n", scanInterval)
	fmt.Println("----------------------------------")

	var lastPriority int = -1

	for {
		rssi, found := getClaroRSSI()
		var targetPriority int

		if !found {
			fmt.Printf("Network %s not found in scan. Setting default low priority.\n", targetSSID)
			targetPriority = 1
		} else if rssi >= StrongSignalDbm {
			fmt.Printf("Strong signal detected (%d dBm). Setting high priority!\n", rssi)
			targetPriority = 10
		} else if rssi <= WeakSignalDbm {
			fmt.Printf("Weak signal detected (%d dBm). Lowering priority.\n", rssi)
			targetPriority = 1
		} else {
			fmt.Printf("Moderate signal detected (%d dBm). Keeping moderate priority.\n", rssi)
			targetPriority = 3
		}

		if targetPriority != lastPriority {
			fmt.Printf("Changing priority: %d -> %d\n", lastPriority, targetPriority)
			if err := generateWpaConf(targetPriority); err != nil {
				fmt.Fprintf(os.Stderr, "Error writing config: %v\n", err)
			} else {
				if err := reloadWpaSupplicant(); err != nil {
					fmt.Fprintf(os.Stderr, "Error reloading wpa_supplicant: %v\n", err)
				} else {
					lastPriority = targetPriority
				}
			}
		} else {
			if found {
				fmt.Printf("No priority change needed. Signal is %d dBm.\n", rssi)
			} else {
				fmt.Println("No priority change needed. Network unavailable.")
			}
		}

		time.Sleep(scanInterval)
	}
}

// getClaroRSSI scans using ifconfig and returns the highest dBm signal found
func getClaroRSSI() (int, bool) {
	cmd := exec.Command("ifconfig", interfaceName, "list", "scan")
	var out bytes.Buffer
	cmd.Stdout = &out

	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error running ifconfig scan: %v\n", err)
		return 0, false
	}

	bestRSSI := -100
	found := false

	lines := strings.Split(out.String(), "\n")
	for _, line := range lines {
		if strings.Contains(line, targetSSID) {
			fields := strings.Fields(line)
			for _, field := range fields {
				if strings.Contains(field, ":") {
					parts := strings.Split(field, ":")
					if len(parts) > 0 {
						if val, err := strconv.Atoi(parts[0]); err == nil {
							if val > bestRSSI {
								bestRSSI = val
								found = true
							}
						}
					}
				}
			}
		}
	}

	return bestRSSI, found
}

func generateWpaConf(priority int) error {
	configContent := fmt.Sprintf(`# Auto-generated by Go wifi_survey
ctrl_interface=/var/run/wpa_supplicant
eapol_version=2
ap_scan=1
fast_reauth=1

# Dynamic Managed Network
network={
    ssid="%s"
    key_mgmt=NONE
    priority=%d
}
`, targetSSID, priority)

	tempPath := wpaConfPath + ".tmp"
	
	err := os.WriteFile(tempPath, []byte(configContent), 0644)
	if err != nil {
		return err
	}

	return os.Rename(tempPath, wpaConfPath)
}

func reloadWpaSupplicant() error {
	cmd := exec.Command("wpa_cli", "-i", interfaceName, "reconfigure")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%v: %s", err, strings.TrimSpace(stderr.String()))
	}
	fmt.Println("wpa_supplicant successfully hot-reloaded.")
	return nil
}
